[package]
name = "headers"
version = "0.0.0" # don't forget to update html_root_url
description = "typed HTTP headers"
readme = "README.md"
homepage = "https://hyper.rs"
license = "MIT"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
keywords = ["http", "hyper", "hyperium"]
categories = ["network-programming", "web-programming::http-client", "web-programming::http-server"]

publish = false

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*"
]

[workspace]
members = [
    "./",
    "headers-core",
    "headers-derive",
    "headers-ext",
]

[dependencies]
#base64 = "0.9"
#bytes = "0.4.4"
headers-core = { path = "./headers-core" }
headers-derive = { path = "./headers-derive" }
headers-ext = { path = "./headers-ext" }
#http = "0.1.7"
#language-tags = "0.2"
#log = "0.4"
#mime = "0.3"
#percent-encoding = "1.0"
#unicase = "2.1"
