[package]
name = "headers-core"
version = "0.0.2" # don't forget to update html_root_url
description = "typed HTTP headers"
repository = "https://github.com/hyperium/headers"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"

[dependencies]
bytes = "0.4"
http = "0.1.13"
